### PR TITLE
Remove CentOS Stream 8

### PR DESCRIPTION
**Pull request by ArtofBugs**

### CODE REVIEW

**Review by ramereth — CHANGES_REQUESTED** [review]
For the spec tests that we use `centos` with no specific version, please change this to `almalinux`

**Review by ramereth — APPROVED** [review]
Please do a patch bump

**Comment by ArtofBugs** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `main` and has automatically performed a patch-level version bump to v1.5.2.  Have a nice day!

**Pull request merged**
